sonar:
  image: siamaksade/sonar
  ports:
    - "9000:9000"
    - "5432:5432"
nexus:
  image: siamaksade/nexus:2.8.1
  ports:
    - "8081:8081"
jenkins:
  build: ./jenkins-ci
  links:
     - nexus:nexus
     - sonar:sonar
  ports:
    - "8080:8080"

